import UndrawCreditCard from './UndrawCreditCard.vue';
import UndrawSocialMedia from './UndrawSocialMedia.vue';
import UndrawMailSent from './UndrawMailSent.vue';
import UndrawSearch from './UndrawSearch.vue';
import UndrawMapDark from './UndrawMapDark.vue';
import UndrawPhoto from './UndrawPhoto.vue';
import UndrawBlogPost from './UndrawBlogPost.vue';
import UndrawCharts from './UndrawCharts.vue';
import UndrawDevices from './UndrawDevices.vue';
import UndrawAtWork from './UndrawAtWork.vue';
import UndrawDelivery from './UndrawDelivery.vue';
import UndrawChat from './UndrawChat.vue';
import UndrawDocuments from './UndrawDocuments.vue';
import UndrawAnalytics from './UndrawAnalytics.vue';
import UndrawPortfolio from './UndrawPortfolio.vue';
import UndrawPlainCreditCard from './UndrawPlainCreditCard.vue';
import UndrawYacht from './UndrawYacht.vue';
import UndrawTabs from './UndrawTabs.vue';
import UndrawImageFolder from './UndrawImageFolder.vue';
import UndrawMobile from './UndrawMobile.vue';
import UndrawPosts from './UndrawPosts.vue';
import UndrawPhotos from './UndrawPhotos.vue';
import UndrawMapLight from './UndrawMapLight.vue';
import UndrawWoman from './UndrawWoman.vue';
import UndrawGettingCoffee from './UndrawGettingCoffee.vue'

export { UndrawCreditCard as UndrawCreditCard };
export { UndrawSocialMedia as UndrawSocialMedia };
export { UndrawMailSent as UndrawMailSent };
export { UndrawSearch as UndrawSearch };
export { UndrawMapDark as UndrawMapDark };
export { UndrawPhoto as UndrawPhoto };
export { UndrawBlogPost as UndrawBlogPost };
export { UndrawCharts as UndrawCharts };
export { UndrawDevices as UndrawDevices };
export { UndrawAtWork as UndrawAtWork };
export { UndrawDelivery as UndrawDelivery };
export { UndrawChat as UndrawChat };
export { UndrawDocuments as UndrawDocuments };
export { UndrawAnalytics as UndrawAnalytics };
export { UndrawPortfolio as UndrawPortfolio };
export { UndrawPlainCreditCard as UndrawPlainCreditCard };
export { UndrawYacht as UndrawYacht };
export { UndrawTabs as UndrawTabs };
export { UndrawImageFolder as UndrawImageFolder };
export { UndrawMobile as UndrawMobile };
export { UndrawPosts as UndrawPosts };
export { UndrawPhotos as UndrawPhotos };
export { UndrawMapLight as UndrawMapLight };
export { UndrawWoman as UndrawWoman };
export { UndrawGettingCoffee as UndrawGettingCoffee };
